#include <windows.h>

#define BROWN		FOREGROUND_RED | FOREGROUND_GREEN
#define BLUE		FOREGROUND_BLUE
#define RED			FOREGROUND_RED
#define GREEN		FOREGROUND_GREEN
#define MAGENTA		FOREGROUND_RED | FOREGROUND_BLUE
#define LGREY		FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN
#define CYAN		FOREGROUND_BLUE | FOREGROUND_GREEN
#define BLACK		0
//Light text colors:
#define YELLOW		FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define LBLUE		FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define LRED		FOREGROUND_RED | FOREGROUND_INTENSITY
#define LGREEN		FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define LMAGENTA	FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define WHITE		FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define LCYAN		FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define GREY		0 | FOREGROUND_INTENSITY
//Dark background colors:
#define B_BROWN		BACKGROUND_RED | BACKGROUND_GREEN
#define B_BLUE		BACKGROUND_BLUE
#define B_RED		BACKGROUND_RED
#define B_GREEN		BACKGROUND_GREEN
#define B_MAGENTA	BACKGROUND_RED | BACKGROUND_BLUE
#define B_LGREY		BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_GREEN
#define B_CYAN		BACKGROUND_BLUE | BACKGROUND_GREEN
#define B_BLACK		0
//Light background colors:
#define B_YELLOW	BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define B_LBLUE		BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define B_LRED		BACKGROUND_RED | BACKGROUND_INTENSITY
#define B_LGREEN	BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define B_LMAGENTA	BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define B_WHITE		BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define B_LCYAN		BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define B_GREY		0 | BACKGROUND_INTENSITY

#define DEFAULT		LGREY | B_BLACK


// And heres a code snippet to set the color 

void SetColor(int color) {
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),color);
}
